# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_auto_20171107_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('password', models.CharField(help_text='<a href="password">\u4fee\u6539\u5bc6\u7801</a>', max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'permissions': (('show_table', '\u67e5\u770btable'),),
            },
        ),
        migrations.CreateModel(
            name='All_api_for_k8s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'api\u540d\u79f0',
                'verbose_name_plural': 'api\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_type', models.SmallIntegerField(choices=[(0, 'alias'), (1, 'absolute_url')], default=0)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '\u83dc\u5355',
                'verbose_name_plural': '\u83dc\u5355',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('menus', models.ManyToManyField(blank=True, to='k8sproject.Menu')),
            ],
            options={
                'verbose_name_plural': '\u89d2\u8272',
            },
        ),
        migrations.CreateModel(
            name='Show_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=32)),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8sproject.Menu', verbose_name='\u83dc\u5355\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9700\u8981\u663e\u793a\u7684\u83dc\u5355',
                'verbose_name_plural': '\u9700\u8981\u663e\u793a\u7684\u83dc\u5355',
            },
        ),
        migrations.AddField(
            model_name='all_api_for_k8s',
            name='menu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8sproject.Menu', verbose_name='\u83dc\u5355\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='k8sproject.Role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
