# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sproject', '0003_auto_20180610_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_api_for_k8s',
            name='result_from_api_name',
            field=models.TextField(max_length=10240, verbose_name='\u6240\u6709\u8fd4\u8fd8\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'alias'), (1, 'absolute_url')]),
        ),
    ]
