# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sproject', '0004_auto_20180610_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_result_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace_name', models.CharField(max_length=32, verbose_name='\u547d\u540d\u7a7a\u95f4')),
            ],
            options={
                'verbose_name': '\u6240\u6709\u8fd4\u8fd8\u7ed3\u679c',
                'verbose_name_plural': '\u6240\u6709\u8fd4\u8fd8\u7ed3\u679c',
            },
        ),
        migrations.AddField(
            model_name='all_api_for_k8s',
            name='namespace_type',
            field=models.ManyToManyField(to='k8sproject.all_result_info', verbose_name='\u6240\u5c5e\u547d\u540d\u7a7a\u95f4'),
        ),
    ]
