# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k8sproject', '0005_auto_20180610_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_from_api_name', models.TextField(max_length=10240, verbose_name='\u6240\u6709\u8fd4\u8fd8\u7ed3\u679c')),
            ],
            options={
                'verbose_name': '\u8fd4\u8fd8\u7ed3\u679c',
                'verbose_name_plural': '\u8fd4\u8fd8\u7ed3\u679c',
            },
        ),
        migrations.RenameModel(
            old_name='all_result_info',
            new_name='namespace',
        ),
        migrations.AlterModelOptions(
            name='namespace',
            options={'verbose_name': '\u547d\u540d\u7a7a\u95f4', 'verbose_name_plural': '\u547d\u540d\u7a7a\u95f4'},
        ),
        migrations.RemoveField(
            model_name='all_api_for_k8s',
            name='namespace_type',
        ),
        migrations.RemoveField(
            model_name='all_api_for_k8s',
            name='result_from_api_name',
        ),
        migrations.AddField(
            model_name='result',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8sproject.namespace'),
        ),
    ]
