# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sproject', '0007_auto_20180610_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_from_api_name',
            field=models.TextField(blank=True, max_length=10240, null=True, verbose_name='\u6240\u6709\u8fd4\u8fd8\u7ed3\u679c'),
        ),
    ]
